<?xml version="1.0" encoding="utf-8"?><Database Name="QLSACH" Class="LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VC4KFV7;Initial Catalog=QLSACH;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLSACHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="IDSach" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LoaiSach" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TacGia" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NhaXuatBan" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>